# Generated by Django 5.0.6 on 2024-07-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_address_item_agency_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pagibig_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sss',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tin',
        ),
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='pag_ibig_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='place_of_birth',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='sss_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='tin_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
