# Generated by Django 5.0.6 on 2024-07-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_pagibig_id_remove_item_sss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='birthday',
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
    ]
